# golangci-lint configuration
# Reference: https://golangci-lint.run/docs/configuration/file/

version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  sort-order:
    - linter
    - severity
    - file

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/mountain-reverie/mikrotik-configuration-backup

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused constants, variables, functions and types

    # Additional recommended linters
    - asasalint     # Check for pass []any as any in variadic func
    - asciicheck    # Check for non-ASCII identifiers
    - bidichk       # Check for dangerous unicode character sequences
    - bodyclose     # Check HTTP response body is closed
    - copyloopvar   # Detects places where loop variables are copied
    - cyclop        # Check function and package cyclomatic complexity
    - dupl          # Code clone detection
    - durationcheck # Check for two durations multiplied together
    - errname       # Check error naming conventions
    - errorlint     # Find code that will cause problems with error wrapping
    - exhaustive    # Check exhaustiveness of enum switch statements
    - forbidigo     # Forbid specific identifiers
    - funlen        # Detect long functions
    - gochecknoglobals # Check that no global variables exist
    - gochecknoinits   # Check that no init functions are present
    - gocognit      # Compute and check cognitive complexity
    - goconst       # Find repeated strings that could be constants
    - gocritic      # Comprehensive Go source code linter
    - gocyclo       # Compute cyclomatic complexity
    - godot         # Check if comments end in period
    - gomoddirectives # Manage replace, retract directives in go.mod
    - goprintffuncname # Check printf-like functions are named correctly
    - gosec         # Security problems
    - intrange      # Find places where range can be simplified
    - loggercheck   # Check key-value pairs for common logger libraries
    - makezero      # Find slice declarations with non-zero initial length
    - mirror        # Reports wrong mirror patterns of bytes/strings
    - mnd           # Detect magic numbers
    - nakedret      # Find naked returns in functions
    - nestif        # Report deeply nested if statements
    - nilerr        # Find code returning nil even if it checks err is not nil
    - nilnil        # Check for simultaneous return of nil error and invalid value
    - noctx         # Find sending HTTP request without context.Context
    - nolintlint    # Report ill-formed or insufficient nolint directives
    - nonamedreturns # Report all named returns
    - nosprintfhostport # Check for sprintf with net host:port
    - perfsprint    # Checks for performance issues with fmt.Sprintf
    - predeclared   # Find code that shadows predeclared identifiers
    - promlinter    # Check Prometheus metrics naming
    - reassign      # Check that package variables are not reassigned
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter
    - sloglint      # Ensure consistent usage of slog
    - spancheck     # Check for mistakes with OpenTelemetry spans
    - sqlclosecheck # Check sql.Rows and sql.Stmt are closed
    - testableexamples # Check if examples are testable
    - testpackage   # Require separate _test package
    - tparallel     # Detect inappropriate usage of t.Parallel()
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters
    - usestdlibvars # Detect the possibility to use variables/constants from stdlib
    - wastedassign  # Find wasted assignment statements
    - whitespace    # Detection of leading and trailing whitespace

  disable:
    - depguard      # Depends on specific project needs
    - exhaustruct   # Too strict for most projects
    - gochecksumtype # Only useful for sum types
    - godox         # Detects TODO/FIXME comments (can be annoying)
    - paralleltest  # Forces t.Parallel() (not always desired)
    - testifylint   # Only useful if using testify
    - varnamelen    # Too opinionated on variable name length
    - wsl           # Too opinionated on whitespace
    - wrapcheck     # Too strict for internal packages

severity:
  default: error
