# GoReleaser configuration
# Reference: https://goreleaser.com/customization/

version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: mikrotik-backup
    main: ./cmd/mikrotik-backup
    binary: mikrotik-backup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - CONTRIBUTING.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Docker images (using v2 format for multi-arch builds)
dockers_v2:
  - ids:
      - mikrotik-backup
    images:
      - "ghcr.io/mountain-reverie/mikrotik-backup"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
    dockerfile: packages/Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "https://github.com/mountain-reverie/mikrotik-configuration-backup"
      "org.opencontainers.image.licenses": "MIT"
      "org.opencontainers.image.description": "Automated backup tool for MikroTik router configurations"
    extra_files:
      - LICENSE
      - README.md

# Sign checksums with cosign using keyless signing
signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    args:
      - "sign-blob"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

# Generate SBOMs for all archives
sboms:
  - id: archive
    artifacts: archive
    documents:
      - '${artifact}.sbom.json'
  - id: source
    artifacts: source
    documents:
      - '${artifact}.sbom.json'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other Changes
      order: 999

release:
  github:
    owner: mountain-reverie
    name: mikrotik-configuration-backup
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## MikroTik Configuration Backup {{ .Tag }}

    Release of mikrotik-backup version {{ .Version }}.

  footer: |
    **Full Changelog**: https://github.com/mountain-reverie/mikrotik-configuration-backup/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Installation

    ### Binary Downloads
    Download the appropriate Linux binary for your system from the assets below.

    ### Go Install
    ```bash
    go install github.com/mountain-reverie/mikrotik-configuration-backup/cmd/mikrotik-backup@{{ .Tag }}
    ```

    ## Docker
    ```bash
    docker pull ghcr.io/mountain-reverie/mikrotik-backup:{{ .Tag }}
    ```
